### ISSUE TITLE
Issue with ldap-ad.py script

### ISSUE THREAD

**Issue by hs-hub-world** [rcanderson23/ldap-ad#1]
Hi, thanks for putting the script together. 

I am experiencing this error when trying to execute the py script, please see image below

![image](https://user-images.githubusercontent.com/20629911/71047548-d9690600-20f0-11ea-93b5-29eda31d91b5.png)

I have made sure the ini file values are correct

Thank you!

**Comment by rcanderson23** [comment]
Sorry you ran into issues. I wrote this for my last job and unfortunately don't have an environment setup to test it anymore. I remember I wrote it so that SSL was required and see that ca_cert isn't present in the sample ini. Looking at the code, it is required. Please try adding ca_cert to the ini equal to the path of the ca of the cert being presented for ldaps.

**Comment by hs-hub-world** [comment]
Thanks for the reply, I'll review the CA param option. We have decided to move on and implemented our in house web service that returns json.  Thanks
